### ISSUE TITLE
書的標題做排序，列完同一本書不同書店的結果

### ISSUE THREAD

**Issue by YuanLiou** [Taiwan-Ebook-Lover/Taiwan-Ebook-Lover.github.io#2]
Via Twitter [Jedi](https://twitter.com/JediLin/status/1078240789619044353)：
> 預設的搜尋結果看起來會 group by store，即列出同一個書店的所有結果後才列出第二個書店的結果。
想要有 group by book title 的呈現方式，即同一個書名列出所有書店的結果後，再列出下一個書名的；或者在搜尋結果筆數多於某個數量時，能夠先只列出書名做篩選

**Comment by focaaby** [comment]
Via Twitter [Jeremy Lu](https://twitter.com/thecat/status/1256905556603727872)
And we replied: 

> 感謝 feedback 目前我們沒有實做精準度，是以各個書城返回的結果為內容。
預計會整理各家廠商第一筆結果作呈現
