### ISSUE TITLE
Page overflow

### ISSUE THREAD

**Issue by x3388638** [Taiwan-Ebook-Lover/Taiwan-Ebook-Lover.github.io#72]
**Describe the bug**
the search result page shows the unexpected x-axis scrollbar when the amount of result items is big enough and shows the y-axis scrollbar

**To Reproduce**
search & go to the search result page

**Expected behavior**

**Screenshots**
<img width="2541" alt="截圖 2022-01-21 下午1 12 49" src="https://user-images.githubusercontent.com/8147952/150470363-313d8a79-d517-4a76-859a-93a6ef4dad5c.png">

**Desktop (please complete the following information):**

- OS: macOS 11.2.3
- Browser: Chrome
- Version: 97.0.4692.71

**Smartphone (please complete the following information):**

**Additional context**
as the attached image, the root cause is the style of the bottom line wrapper for bookstore tabs
should replace the width value `100vw` with `100%` since the 100vw contains the width of the y-axis scrollbar

**Comment by YuerLee** [comment]
@ast850328 要不要試試？

**Comment by lemon5920** [comment]
感謝 YY 大大回饋！！
目前我的環境下無法重現該問題，瀏覽器的 Scrollbar 看起來有做了自動隱藏（見下圖）
不過當時為了實現類似 Google 搜尋結果頁的樣式（一條全寬的實線區隔 header & result），是用了比較 Tricky 的作法，`vw` 涵蓋了 Scrollbar 的寬，的確是有哥反應的這項隱憂。
以目前架構改 `100%` 的話可能無法滿足需求，橫線會過短，這部分可能需要改 Layout，我們再想想怎麼做～

![截圖](https://user-images.githubusercontent.com/13966758/150623050-3dd16cd1-9943-48b5-b093-99d5a7b77ff8.png)
環境：

- OS: macOS 12.1
- Browser: Chrome
- Version: 97.0.4692.99

**Comment by x3388638** [comment]
@lemon5920 因為我`總是`喜歡 scrollbar XD
<img width="655" alt="截圖 2022-01-22 上午11 40 07" src="https://user-images.githubusercontent.com/8147952/150623508-21b7ccb6-54f8-4168-b7cf-e98e669fa073.png">

我昨天是的時候寬度可能太小所以 100% 看起來正常

possible solution:
把那條線移到 tabs 下面用 absolute, left 0, width 100%
![image](https://user-images.githubusercontent.com/8147952/150623633-f731b7dc-be93-4d68-b693-9ff5ce9a3515.png)

**Comment by lemon5920** [comment]
@x3388638 可以重現惹～感謝大大
會再來修，甘溫

**Comment by YuerLee** [comment]
@x3388638 @lemon5920 
用 Windows 即可重現，scrollbar 永遠在。

by 窗粉。
